//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class BusinessUnit
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public BusinessUnit()
    {
        this.NearMissEntries = new HashSet<NearMissEntry>();
    }

    public int busUnitID { get; set; }
    public string unitName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<NearMissEntry> NearMissEntries { get; set; }
}

public partial class Location
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Location()
    {
        this.NearMissEntries = new HashSet<NearMissEntry>();
    }

    public int locationID { get; set; }
    public string locationName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<NearMissEntry> NearMissEntries { get; set; }
}

public partial class NearMissEntry
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public NearMissEntry()
    {
        this.Resolutions = new HashSet<Resolution>();
    }

    public int entryID { get; set; }
    public int userID { get; set; }
    public int busUnitID { get; set; }
    public int locationID { get; set; }
    public Nullable<int> nearMissType { get; set; }
    public System.DateTime dateCreated { get; set; }
    public string subject { get; set; }
    public string finding { get; set; }
    public string status { get; set; }

    public virtual BusinessUnit BusinessUnit { get; set; }
    public virtual Location Location { get; set; }
    public virtual NearMissType NearMissType1 { get; set; }
    public virtual User User { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Resolution> Resolutions { get; set; }
}

public partial class NearMissType
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public NearMissType()
    {
        this.NearMissEntries = new HashSet<NearMissEntry>();
    }

    public int nearMissTypeID { get; set; }
    public string entryType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<NearMissEntry> NearMissEntries { get; set; }
}

public partial class Resolution
{
    public int resolutionID { get; set; }
    public int entryID { get; set; }
    public int approveID { get; set; }
    public string resolutionText { get; set; }

    public virtual NearMissEntry NearMissEntry { get; set; }
    public virtual User User { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class User
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {
        this.NearMissEntries = new HashSet<NearMissEntry>();
        this.Resolutions = new HashSet<Resolution>();
    }

    public int userID { get; set; }
    public string username { get; set; }
    public string email { get; set; }
    public string password { get; set; }
    public int userType { get; set; }
    public string firstName { get; set; }
    public string lastName { get; set; }
    public System.DateTime dateCreated { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<NearMissEntry> NearMissEntries { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Resolution> Resolutions { get; set; }
}
